node_id: relay-b
mode: server

identity:
  cert: ./dev/certs/relay-b.crt
  key: ./dev/certs/relay-b.key
  ca: ./dev/certs/ca.crt

listen: 127.0.0.1:4434

allowed_relay_clients:
  - relay-a

peers:
  - id: relay-a
  - id: relay-c
    address: 127.0.0.1:4435
    dial: true
